### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by saisangu** [angelcervera/osm4scala#27]
Following output is seen when I ran compile on sbt
[info] Resolving jline#jline;2.14.3 ...
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: fileformat.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: osmformat.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
Traceback (most recent call last):
  File "C:\Temp\protocbridge7327161231499492139.py", line 6, in <module>
    s.sendall(content)
TypeError: a bytes-like object is required, not 'str'
[info] Done updating.
[info] Resolving org.scalactic#scalactic_2.12;3.0.1 ...
[info] Updating {file:/C:/Users/kzpt72/osm4scala/osm4scala/}examples-counter-akka...
[info] Resolving org.scala-lang#scala-reflect;2.12.2 ...
[info] Resolving jline#jline;2.14.3 ...
[info] Compiling 1 Scala source to C:\Users\kzpt72\osm4scala\osm4scala\examples\common-utilities\target\scala-2.12\classes...
[info] Done updating.
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[trace] Stack trace suppressed: run last core/compile:protocGenerate for the full output.
[error] (core/compile:protocGenerate) protoc returned exit code: 1
[error] Total time: 8 s, completed Aug 25, 2017 12:31:58 PM

Please let me know if there are additional dependencies I would need to build this.
Thanks

**Comment by angelcervera** [comment]
I'm sorry, but it has been not tested on Microsoft Windows, but [Travis](https://travis-ci.org/angelcervera/osm4scala) is building the project without problems.
Looks like the problem is with protobuf. Are you using version 2.6.1 as said the documentation?

By the way. Do you need to compile the library? It is available in http://dl.bintray.com/angelcervera/maven/com/acervera/osm4scala/ and you can use it directly using sbt or your preferred dependencies manager. It is in the documentation.

**Comment by angelcervera** [comment]
No response and no problems building in Travis
